steps:
  mtaBuild:
    dockerImage: 'ppiper/mta-archive-builder:latest'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'cf'
      apiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
      org: 'abc'
      space: 'def'
