steps:
  mtaBuild:
    dockerImage: 'ppiper/mta-archive-builder:latest'
  neoDeploy:
    deployMode: mta
    neo:
      dockerImage: 'ppiper/neo-cli'
      account: 'aeba5bf84'
      credentialsId: 'CI_CREDENTIALS_ID'
      host: 'hana.ondemand.com'
 
