steps:
  mtaBuild:
    dockerImage: 'ppiper/mta-archive-builder:latest'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'neo-credentials'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'piper'
      space: 'demo'
