steps:
  mtaBuild:
    dockerImage: 'ppiper/mta-archive-builder:latest'
  neoDeploy:
    dockerImage: 'ppiper/neo-cli'
    account: 'aeba5bf84'
    credentialsId: 'neo-credentials'
    host: 'hana.ondemand.com'
 
