steps:
  mtaBuild:
    dockerImage: 'ppiper/mta-archive-builder:latest'
  neoDeploy:
    dockerImage: 'ppiper/neo-cli'
    account: 'p1943039741'
    credentialsId: 'neo-credentials'
    host: 'hanatrial.ondemand.com'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'cf'
      apiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
      org: 'piper'
      space: 'demo'
